version: '3.8'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network

  tomcat:
    image: tomcat:9.0-alpine
    ports:
      - "8080:8080"
    depends_on:
      - build
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
